name: students_control
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  animated_search_bar: ^2.8.0
  bcrypt: ^1.1.3
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.2.3
  go_router: ^17.0.0
  path: ^1.9.1
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/icons/
